### PR TITLE
add parameter parsing on build + parameter getter

### PR DESCRIPTION
**Pull request by clux**
An extra independent thing.

Needed to filter jobs based on a parameter property that wasn't parsed.

The types of the embedding `actions` struct are a bit dynamic & dubious, but with enough `serde` `default` attrs we can parse them as well :smile:

### CODE REVIEW

**Comment by mockersf** [comment]
thanks, I saw those and didn't know their use and their model... If the action._class can be missing, wouldn't it be better as an Option<String> ?

**Comment by clux** [comment]
Ah, yes, you're right. I only normally use those style defaults with optional vectors, because `None` and `is_empty` usually mean the same thing, and nesting the checks can feel a bit annoying.

I'll change the string param.

**Comment by clux** [comment]
There we go, one extra nesting check turned out to be needed.

**Comment by mockersf** [comment]
I've read the source of Jenkins a little, it seems a parameter can be one of `BooleanParameterValue`, `FileParameterValue`, `JobParameterValue`, `ParametersAction`, `PasswordParameterValue`, `RunParameterValue`, `StringParameterValue` or `TextParameterValue`
And an action a `CauseAction` or a `ParametersAction` or maybe `AbstractScmTagAction`, `Fingerprinter`,  `SCMTrigger` but those last three are not in the same package of jenkins so maybe not.

I think those should be represented as [internally tagged Enums](https://serde.rs/enum-representations.html#internally-tagged) to avoid the `if`s in get_parameters, and the potential empty array if we have something unexpected, or the `serde_json::Value` in `Parameter` that will have to be parsed at the library consumer.

That's quite a bit more work to do, I'll take a look at it this week end if you don't have time before.

**Comment by clux** [comment]
Ooh, that's pretty nice. The `serde_json::Value` export seemed a bit annoying to me as well.

Is it possible to reuse the internal `_class` tag for this to parse straight into the right struct with tagged enums? The `_class` tag contains dot delimited class names after all.

Not sure I'll have too much time to look at this, but maybe able to give it a short go tomorrow.

**Comment by mockersf** [comment]
Ok it wasn't as simple as using an internally tagged enum from serde...

The list of valid `_class` values can be extended by Jenkins plugins, and serve gives an error when it can't match the son to one of the variant...

I wrote a macro that implements Deserialise for an internally tagged enum allowing a default variant if none matches, plus [a few of the basic variants](https://github.com/mockersf/jenkins-api.rs/commit/6596cff1069f542a394e23450cae7e865160575a).

The following json:
```json
   "actions" : [
      {
         "_class" : "hudson.model.CauseAction",
         "causes" : [
            {
               "_class" : "hudson.triggers.SCMTrigger$SCMTriggerCause",
               "shortDescription" : "Started by an SCM change"
            }
         ]
      },
      {},
      {
         "buildsByBranchName" : {
            "refs/remotes/origin/master" : {
               "revision" : {
                  "branch" : [
                     {
                        "name" : "refs/remotes/origin/master",
                        "SHA1" : "cf0b57889bf8773551b8d21578ea7c8b9bb1acfc"
                     }
                  ],
                  "SHA1" : "cf0b57889bf8773551b8d21578ea7c8b9bb1acfc"
               },
               "buildNumber" : 8,
               "buildResult" : null,
               "marked" : {
                  "SHA1" : "cf0b57889bf8773551b8d21578ea7c8b9bb1acfc",
                  "branch" : [
                     {
                        "name" : "refs/remotes/origin/master",
                        "SHA1" : "cf0b57889bf8773551b8d21578ea7c8b9bb1acfc"
                     }
                  ]
               },
               "_class" : "hudson.plugins.git.util.Build"
            }
         },
         "remoteUrls" : [
            "https://github.com/mockersf/jenkins-api.rs.git"
         ],
         "lastBuiltRevision" : {
            "branch" : [
               {
                  "SHA1" : "cf0b57889bf8773551b8d21578ea7c8b9bb1acfc",
                  "name" : "refs/remotes/origin/master"
               }
            ],
            "SHA1" : "cf0b57889bf8773551b8d21578ea7c8b9bb1acfc"
         },
         "scmName" : "",
         "_class" : "hudson.plugins.git.util.BuildData"
      },
      {
         "_class" : "hudson.plugins.git.GitTagAction"
      },
      {},
      {}
   ],
```

get deserialised as:
```rust
actions: [
            CauseAction {
                causes: [
                    SCMTriggerCause {
                        short_description: "Started by an SCM change"
                    }
                ]
            },
            Default {
                class: None
            },
            Default {
                class: Some(
                    "hudson.plugins.git.util.BuildData"
                )
            },
            Default {
                class: Some(
                    "hudson.plugins.git.GitTagAction"
                )
            },
            Default {
                class: None
            },
            Default {
                class: None
            }
        ]
```

I still have a few improvements to do on the macro, and maybe add a few more variants for the enums.

Maybe start the discussion with serve if they are interested in adding an attribute to not return an error on no matching variant, or allowing a default.

What do you think ?

**Comment by clux** [comment]
Nice work! That macro is a beast, but the deserialisation format does look very nice! I'll try out 0.2.1  and kill this PR if it's straight forward today :+1:

**Comment by clux** [comment]
Have tried it out now. It does parse everything. Had to do this awkward thing on the app side to get the dictionary of string parameters though:

```rust
fn get_string_params(b: &Build) -> BTreeMap<String, String> {
    let mut res = BTreeMap::new();
    for a in &b.actions {
        match a {
            &Action::ParametersAction { ref parameters } => {
                trace!("got pars {:?}", parameters);
                for p in parameters {
                    match p.clone() {
                        &Parameter::StringParameterValue { ref name, ref value } => {
                            res.insert(name.to_string(), value.to_string());
                        },
                        _ => {}
                    }
                }
            },
            _ => {}
        }
    }
    res
}
```

there's probably a better way, but that's enough borrow checker for today. I'll close this pr now. Thank you!

**Comment by mockersf** [comment]
If you don't care about the other branches, I find that `if let` is easier to read than `match`.

Also, instead of cloning the parameters and then using `to_string` on the name / value to switch them from `&String` to `String`, you can directly clone the names / values to get `Strings`.

```rust
pub fn get_string_params(b: &Build) -> BTreeMap<String, String> {
    let mut res = BTreeMap::new();
    for a in &b.actions {
        if let &Action::ParametersAction { ref parameters } = a {
            trace!("got pars {:?}", parameters);
            for p in parameters {
                if let &Parameter::StringParameterValue { ref name, ref value } = p {
                    res.insert(name.clone(), value.clone());
                }
            }
        }
    }
    res
}
```

**Comment by mockersf** [comment]
v0.2.1 is published on crates.io

**Comment by clux** [comment]
Awesome, removed my git pin :-)
And  yeah, `if let` is a lot nicer. Thanks for all the help.

**Pull request closed without merging**
